### ISSUE TITLE
Libft linking

### ISSUE THREAD

**Issue by pulgamecanica** [benmaia/42_So_Long#1]
https://github.com/benmaia/42_So_Long/blob/10e7e86271c0f3ecc601e6b5fbb6c93629b4fd06/so_long/Makefile#L43

To use a library you should link the library with the appropiate flags, hence you should never compile with the library "FILE (.../libft.a)" path....
Therefore, somewhere in your Makefile file you should have "**-lft**"...

**Comment by benmaia** [comment]
All fixed, thank you very much for the tip!
